theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: /assets/images/logo.png
    footer: /assets/images/typo.png

  image_sizes: 
    sections:
      events:
        hero_single:
          mobile:   400
          tablet:   1024
          desktop:  1920
